development:
  adapter: postgresql
  encoding: unicode
  database: flashcards_postgres_development
  pool: 5
  username: appuser
  password: test1234
  
test:
  adapter: postgresql
  encoding: unicode
  database: flashcards_postgres_test
  pool: 5
  username: appuser
  password: test1234
